### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by jmg-74** [facebookresearch/pytorch-dp#17]
The link just after "May, 11, 2020" should be
https://github.com/facebookresearch/pytorch-dp/blob/master/torchdp/scripts/compute_dp_sgd_privacy.py
instead of 
https://github.com/facebookresearch/pytorch-dp/blob/master/torchdp/compute_dp_sgd_privacy.py
(without /scripts in path) since the target has been moved into script/ subdir.

**Comment by ashkan-software** [comment]
Thank you for pointing this out. Will fix now :)
