### ISSUE TITLE
Generate tarball release

### ISSUE THREAD

**Issue by rluria14** [facebookresearch/pytorch-dp#18]
##  Feature

Since there are no tarball files released for this package here on GitHub or on PyPi, is it possible to generate/compile one either here or on pypi. Working on building this for conda-forge.

Thank you!

**Comment by karthikprasad** [comment]
Hi @rluria14 , thanks for this issue. We are making a minor refactoring to the codebase and will be creating a bundle soon after (and also publish on PyPi). I will comment here once that is done so that you know when to pick it up.

**Comment by rluria14** [comment]
@karthikprasad thanks!

**Comment by karthikprasad** [comment]
The release is now out https://github.com/facebookresearch/pytorch-dp/releases/tag/v0.1-beta.1

**Comment by rluria14** [comment]
> The release is now out https://github.com/facebookresearch/pytorch-dp/releases/tag/v0.1-beta.1

perfect, thanks again.
