### ISSUE TITLE
pip install fails with the cloned repo

### ISSUE THREAD

**Issue by mossadhelali** [facebookresearch/pytorch-dp#23]
Hi,
Thanks for your efforts.
Just wanted to report that cloning the repo and installing using `pip install .` fails with the following error:

>     ERROR: Command errored out with exit status 1:
>      command: /mhelali/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-qh3uxtnj/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-qh3uxtnj/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-qh3uxtnj/pip-egg-info
>          cwd: /tmp/pip-req-build-qh3uxtnj/
>     Complete output (7 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-req-build-qh3uxtnj/setup.py", line 12, in <module>
>         long_description = fh.read()
>       File "/mhelali/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1783: ordinal not in range(128)
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

The issue is fixed by adding `encoding="utf8"` to lines 11 and 15 of setup.py

**Comment by Anonymani** [comment]
Thanks for flagging this issue. I assume this is a misc. system setting issue. We will add encoding just to be safe.
