### ISSUE TITLE
Why the sensitivity is C?

### ISSUE THREAD

**Issue by inch307** [facebookresearch/pytorch-dp#32]
I read Abadi's paper and this code, but I can't understand why the sensitivity is C. 
As the maximum distance of clipped gradient is 2C for two datasets differing one data, I think sensitivity should be 2C.
I agree that C is enough for sensitivity, but I think 2C is more strict and appropriate to be sensitivity.
Thanks.

**Comment by ffuuugor** [comment]
If I recall correctly, we consider two datasets different by one added entity, not replaced. The term "adjacent dataset" refers to the original dataset with one record either added or removed. 
In case of replacement sensitivity is indeed 2C, but that's not the model uses in the paper / our code.

**Comment by inch307** [comment]
Thank you for your reply! I got that replacement sensitivity.

**Comment by mr-lz** [comment]
sorry，I still don't understand why addition/removal sensitivity is C.

**Comment by ffuuugor** [comment]
Can you elaborate on what do you think it should be?

C is `max_grad_norm` - i.e. a maximum value a per sample gradient can take. By definition, this is the maximum amount one single data point can contribute to an overall gradient over a batch. Removing a sample from a batch, therefore, will change the summed gradient by at most C.

NB: in case of averaging gradient over a batch (which is the most common use case), the actual sensitivity is `C/batch_size`

**Comment by mr-lz** [comment]
oh, I get it, thank you! I thought it was the sensitivity of **g(xi)**, but it's actually the sensitivity of **Σg(xi)**.
