### ISSUE TITLE
MNIST example transform

### ISSUE THREAD

**Issue by astorfi** [facebookresearch/pytorch-dp#6]
Hi,

In the [mnist example](https://github.com/facebookresearch/pytorch-dp/blob/master/examples/mnist.py), why do you use the following transform and what's the reason behind those numbers:

`transforms.Normalize((0.1307,), (0.3081,))`

Thank you

**Comment by Darktex** [comment]
This tracks the [MNIST example](https://github.com/pytorch/examples/blob/master/mnist/main.py#L105) in PyTorch.

**Comment by astorfi** [comment]
Sorry if I could not convey what I meant.
I understand it tracks that. My question is why 0.1307 and 0.3081?
Thank you

**Comment by JohnlNguyen** [comment]
0.1307 and 0.3081 are the global mean and standard deviation of the MNIST dataset. Typically you normalize by the global mean and standard deviation in the transform

**Comment by astorfi** [comment]
Thank you.
